include:
- hello.py
kind: ArchiveUploadSpec
name: hello-py-JOLJ

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hellopythonss-d9129e90-9719-4d84-8255-bafa318dc6f7
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://hello-py-JOLJ
  environment:
    name: python-env
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-08-21T16:08:05Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hellopythonss
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python-env
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: hellopythonss-d9129e90-9719-4d84-8255-bafa318dc6f7
      namespace: ""
  requestsPerPod: 1
  resources: {}
